spring:
  application:
    name: kotlin-book-store
  datasource:
    url: "jdbc:postgresql://localhost:5432/kotlin-book-store"
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: false
  flyway:
    enabled: false
    locations: "classpath:db/migration,classpath:user"